name: git push into another repository to deploy to vercel

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: push
        run: |
          git config --global user.email ${{ secrets.SMTC_ACCOUNT_EMAIL }}
          git config --global user.name ${{ secrets.SMTC_ACCOUNT_USERNAME }}
          git init
          git add .
          git commit -m "Merge"
          git remote add origin https://github.com/showmethatcode-official/devwiki-client.git
          git push -u origin main
